### ISSUE TITLE
MsQueue::pop pins epoch until return

### ISSUE THREAD

**Issue by alexcrichton** [crossbeam-rs/crossbeam#103]
The `MsQueue::pop` currently [starts with](https://github.com/aturon/crossbeam/blob/bf1fb5627d67582a53ef712e8cb07fb9ebf878fa/src/sync/ms_queue.rs#L242) a call to `epoch::pin`. This I believe will prevent collection until the method returns, which could potentially take quite a long time (due to the blocking behavior). 

I *think* it may be possible to just drop the epoch [in the blocking case](https://github.com/aturon/crossbeam/blob/bf1fb5627d67582a53ef712e8cb07fb9ebf878fa/src/sync/ms_queue.rs#L298-L301), but that may be naive, so I'd want to think through this some more.

**Comment by jeehoonkang** [comment]
Hmm, I think `pop()` should continue to hold a `guard` even for the blocking case.  Otherwise, `tail` (`tail_shared` in the current master) can be arbitrarily stale if `pop()` releases its guard and calls `thread::park()`.  Thus when `pop()` wakes up from `thread:park()`, `tail` may already have been deallocated and `pop()` invokes undefined behavior by reading a deallocated memory cell.

**Comment by martinhath** [comment]
I think @alexcrichton means dropping the guard before spinning on `while !signal.ready.load(Acquire)`, since whatever is read in that `Ok` block is allocated on the threads stack anyways. 

Like this (from line 296):

```Rust
match self.push_internal(&guard, tail, node) {
    Ok(()) => {
        drop(guard);
        while !signal.ready.load(Acquire) {
            thread::park();
        }
        return signal.data.unwrap();
    }
    Err(n) => {
        node = n;
    }
}
```
