### ISSUE TITLE
Add `with_capacity` constructor

### ISSUE THREAD

**Issue by josecelano** [crossbeam-rs/crossbeam#1100]
See: https://docs.rs/skiplist/latest/skiplist/skipmap/struct.SkipMap.html#method.with_capacity

Does it make sense to add a constructor to pre-allocate items in the skip list like in the [other implementation](https://docs.rs/skiplist/latest/skiplist/skipmap/struct.SkipMap.html#method.with_capacity).

```rust
use skiplist::SkipMap;

let mut skipmap = SkipMap::with_capacity(100);
skipmap.extend((0..100).map(|x| (x, x)));
```

[I'm using the SkipMap](https://github.com/torrust/torrust-tracker/pull/778), and I wonder if the application would be faster adding items, if we pre-allocated memory.

**Comment by taiki-e** [comment]
> [I'm using the SkipMap](https://github.com/torrust/torrust-tracker/pull/778), and I wonder if the application would be faster adding items, if we pre-allocated memory.

I don't think this is true due to our SkipList's current mechanism (not that it employs the exact same mechanism, but BTreeMap doesn't have this function either), but if someone comes up with a specific allocation optimization strategy, we can consider adopting it.

Also note that the skiplist you linked to is a single-threaded skiplist and our skiplist is concurrent skiplist.
