### ISSUE TITLE
binaries are too generic

### ISSUE THREAD

**Issue by ignatenkobrain** [crossbeam-rs/crossbeam#111]
When you do `cargo install crossbeam`, you end up having `bench` and `stress-msq` in your path. This is not very good idea.

Given that it's some bench things, probably it should be only built when running benches and never installed?

**Comment by ignatenkobrain** [comment]
@stjepang ping

**Comment by Bobo1239** [comment]
crossbeam isn't intented to be `cargo install`ed as it's a library and should get included by adding an entry into your project's `Cargo.toml`. The only reason that they are binaries instead of benches, is that [benches are currently still unstable](https://github.com/rust-lang/rust/issues/29553).

**Comment by ignatenkobrain** [comment]
Hmm, you could have used https://crates.io/crates/bencher

**Comment by stjepang** [comment]
We should just move those benchmarks and stress tests into the `examples` directory or inside a special subcrate (e.g. similar to `rayon-demo`).

**Comment by jeehoonkang** [comment]
I made a PR on this issue.  Instead of moving `/src/bin` to `/examples`, I moved it to `/benches`.

These code is somewhat outdated: anyway, the queue implementations are somewhat outdated by the `corssbeam-channel` crate.  Maybe an easier (and saner) way to resolve this issue is just removing `/src/bin`.

**Comment by stjepang** [comment]
We've removed binaries from the repo. Closing.
