### ISSUE TITLE
Guidelines for merging

### ISSUE THREAD

**Issue by arthurprs** [crossbeam-rs/crossbeam#124]
Opening an issue so we can discuss guidelines for merging PRs (not to be confused with "what belongs to crossbeam crate or not").

**Comment by arthurprs** [comment]
A fell like a two maintainers (other than the author) approval is the way to go. Since we are a big group we might even push this number to three.

**Comment by schets** [comment]
I think making master a [protected branch](https://help.github.com/articles/about-protected-branches/) is a good idea, since it enforces these guidelines comes with all sorts of 'oops' protections

**Comment by arthurprs** [comment]
I went ahead and protected master as it seems to be a no-brainer.

**Comment by aturon** [comment]
I agree with the two reviewers approach, and think that people should feel free to request additional reviews in particularly subtle cases.

For broader design/direction questions, I'd suggest following a basic consensus-based approach: file an issue on the repo laying out your proposal and rationale, tag in the other maintainers, and ensure no-one has a "blocking objection" before going forward. (Basically similar to how the Rust subteams work, but lighter weight).

**Comment by stjepang** [comment]
@aturon @alexcrichton  Since you have a lot of experience with project leadership, I'd love to get some thoughts from you. We have a strong Crossbeam team now, but it really needs help with logistics.

Recently we've had multiple discussions on a new GC and new scalable data structures.

I did a lot of prototyping during the last several months, have laid out my ideas for a new GC design, and got valuable feedback from the crossbeam project members (especially @jeehoonkang, @schets, and @arthurprs). The feedback was usually positive, but there were plenty of objections as well. Even @aturon said he agreed with "at least some" of the ideas. :) But we've yet to write some actual code.

I believe at this point we should write up a roadmap and build a strong epoch-based foundation for the future. Because this is a complex topic with a lot of tradeoffs to be made, I'd like us to reach consensus ASAP and come up with a written design everyone is happy with.

Personally, I'm very fond of Rust's RFC process and would like to see one for the Crossbeam team. Shall we create a `crossbeam-rs/rfcs` repo, submit several PR's with detailed designs and reach consensus among the members (or at least the most active ones)? Or maybe just create a a PR for a `DESIGN.md` within this repository?

I'd like to kick off with two RFCs:

1. Sound and flexible `Atomic` API design. The current API is too permissive, and relaxed orderings can cause data races (i.e. memory unsafety) in safe code.
2. Faster, more eager, destructor-supporting, incremental epoch-based GC. The current one performs pinning suboptimally, which is prohibitive in some use cases.

The item (2) is currently blocked on some benchmarking with weaker memory models. I'm going to rent a cheap ARM machine and through benchmarking smoothen the rough edeges around my GC.

As soon as we come up with a design for (1) and (2), we're golden. We'll already have implementation ready (mostly from the `coco` crate), so there won't be much waiting. This will give us a solid core for crossbeam, and then we can more easily split the work and branch off in various directions.

Here are some things I'd like to talk about after that:

3. Deque improvements (see the `coco` crate).
4. Concurrent skiplist API. (by then I'll already have a working implementation)
5. New queues and channels. (I'm implementing this ATM)
6. Concurrent B-trees. (I have some ideas)

Here are some topics I haven't researched thoroughly, but are fit for Crossbeam:

7. Lock-free hash maps.
8. Concurrent radix trees.
9. Flat combining.
10. Elimination back-off.

Alternative GCs (maybe useless, but maybe not):

11. Hazard pointers.
12. Lock-free RC-based GC (like `ArcCell`, but better).

I'm sure some of you have even more ideas!

I'm fully ready to write detailed RFCs for items (1) to (6).
Here are some time estimates for design and implementation:

* (1) and (2) need 2-4 weeks
* (3) needs 1 week
* (4) needs 1 month
* (5) needs 1 month
* (6) needs 3 months

The other two pillars of concurrency in Rust, namely Rayon and Tokio, are seeing great progress. They may also benefit from Crossbeam, so let's not fall behind. ;)

I'm sitting in `#crossbeam` on irc.mozilla.org. Let's hang out! Perhaps this could be our official channel?

**Comment by arthurprs** [comment]
(1) to (2) sound like a no-brainer to me and it's necessary to unblock the other things. Anything me/others can do to speedup that?

I'd :+1: a simplified RFC style process. No need to go full blown here.

I won't really go into the other points because it might deviate the discussion from the important stuff.

**Comment by schets** [comment]
I have a test version of an incremental GC that works with the existing epoch system, and at least one of the commits for (1) is pretty easy.

For (9), I'm working on a Rust translation of [this library](https://github.com/schets/c_flat_combining).

What did you have in mind for (5)?

Also, should we break crossbeam into different crates (epoch, data structures, scoped threads) instead of having this one mega-repo?

**Comment by aturon** [comment]
@stjepang Wow, thank you *so much* for stepping up to lead! What you've outlined sounds fantastic. Let me leave a few thoughts based on my experience.

First, the most vital thing about the RFC process is that there's a **clear space** for stakeholders to discuss proposals before they land, and that consensus among the decision-makers is reached before the proposal lands. Everything else (like the venue) is secondary. Like @arthurprs, I think we should start as simple as possible, but it is important that we have room for distinct threads on distinct topics (so something involving a PR is good). Honestly, it probably makes sense to follow Rust's lead here and make a dedicated RFC repo with a (simplified) template, but just keep the process around it lightweight.

I think right now we're in a space where momentum is essential, so we need to avoid striving for perfection up front, and feel free to experiment. Consensus processes can work well for that: consenting doesn't mean "I believe this is perfect and my ideal proposal", but rather "My objections aren't strong enough to block going in this direction".

To make this work well, it's best to have a relatively small number of very involved decision-makers who must reach consensus (and of course *everyone* is welcome to comment). I wonder if, of the people who stepped up to help with maintenance, we can find a subset of folks who want to push hard on finding a shared vision. It can also help to have a designated "leader", a role I think you may be very well cut out for. 

Now, regarding the vision you've laid out: I really couldn't agree more. The steps you've outlined are exactly what I've always hoped crossbeam would turn into. I know the devil is in the details, and we need to get on the same page there, but it'd be good for something like this "roadmap" to serve as the first RFC.

**Comment by alexcrichton** [comment]
I'd basically just echo @aturon's thoughts, although he's far more eloquent than I :)

**Comment by stjepang** [comment]
Thank you so much for the advice, this is really helpful! :)

I'll create a new repo for a simplified RFC process and write up several proposals over the next few days. Let's get started.

**Comment by nikomatsakis** [comment]
I'm excited! I'd love to have more toys to play with in Rayon. =) 

(Flat combining is one area I've been wanting to explore in particular; my experiments in Rayon showed significant wins, and it can make things a lot easier when building complex combinators. I'm still unsure whether it makes sense to build flat-combining in Rayon (as I've been toying with in https://github.com/nikomatsakis/rayon/pull/141) or to do it in a library like crossbeam.)

**Comment by schets** [comment]
@nikomatsakis There's an old standing issue in crossbeam for flat combining #63 and I've restarted work on it as well. I think the use case for Rayon is fairly different (extremely high contention for the lifetime of the combiner, lots of available work from a consistent subset of threads) so I'm not sure if it should use the same approach as a general purpose flat combining library would.

**Comment by nikomatsakis** [comment]
@schets indeed, that is the question. Another advantage that Rayon has *right now* is knowing that there is a fixed pool of threads (more or less) that are active. But it seems plausible to me that one could design a general purpose flat-combiner that performs "good enough".

**Comment by jeehoonkang** [comment]
I think now we can close this, as we have the RFC repo.
