### ISSUE TITLE
Destructors

### ISSUE THREAD

**Issue by sorear** [crossbeam-rs/crossbeam#13]
I've been thinking about how I might use crossbeam::mem to implement a concurrent hash table.  The current examples of stacks and queues are actually somewhat special, because values can be moved into and out of them, but are never borrowed.  In contrast with a hash table I want to be able to read it without modifying, which requires borrows; but if a value is borrowed from a hash table and then deleted from it in another thread, the `drop()` call needs to be deferred until garbage collection.

Currently crossbeam only supports freeing memory after the grace period.  It seems like it could probably be modified to call destructors, but there might be some interesting caveats / possible unsafeties.  One obvious thing is that a drop call can free an arbitrary amount of memory, so intelligently batching them becomes more difficult (if an object is holding on to 20MiB of memory, we want to free it ASAP, not after 64 epochs).

**Comment by schets** [comment]
I'm working on that [here](https://github.com/schets/crossbeam/tree/destructors)

>  In contrast with a hash table I want to be able to read it without modifying, which requires borrows; but if a value is borrowed from a hash table and then deleted from it in another thread, the drop() call needs to be deferred until garbage collection.

It's only safe to read (and borrow) from a datastructure like the hashtable while you know the data can't be freed - in this case, that means while a Guard is active. Likewise, it's only safe to call drop during garbage collection since it invalidates the region of memory.

> Currently crossbeam only supports freeing memory after the grace period. It seems like it could probably be modified to call destructors

This is pretty simple - 

> (if an object is holding on to 20MiB of memory, we want to free it ASAP, not after 64 epochs)

As it stands now, local garbage is freed whenever a pin call believes that it can and global garbage is freed whenever the epoch is advanced. Threads could be more forceful about advancing the epoch - GC thresholds could consider the garbage size so a large value doesn't sit waiting while no epochs advance and a flag could exist to pressure threads to advance the global epoch when putting lots of memory in global garbage.

However, any calls to free/drop must wait until it's safe (two epochs have advanced) and as of now epochs only advance when a call to pin decides to. In [this branch](https://github.com/schets/crossbeam/blob/gcless_pin/src/mem/epoch/mod.rs#L401), one of the functions I'm adding allows one to force attempts at GC and epoch advancement - if one knowingly unlinks a big object, this function could be called until enough epochs have advanced ( I'm working on the update that returns whether a GC actually ran or not).

I think that intelligent batching of drop/frees is too complicated for now - adding stuff to consider garbage size and allowing the programmer to force advancement is probably good enough for now.

**Comment by drbo** [comment]
One approach to handling such situations is to have the API take a closure as argument, and to pass a borrowed reference to the closure.

**Comment by Vtec234** [comment]
Ok, so I asked people on IRC about this and deferred destruction is ~fairly~ ~quite~ __really__ complicated. There are several problems. First, there is no way to assert that a type has a trivial destructor (one that does literally nothing) statically. There is an unsafe, unstable method for this, `std::intrinsics::needs_drop`. Your trait requirement for `T: Drop` for `unlinked_drop<T>` is too restrictive - a type can have members that need destructors, but not itself be `Drop`. It will always be `needs_drop` though.

Then, for types that are `needs_drop`, asserting `unlinked` is more subtle than for types with trivial destructors. One problem is that they can refer to the local scope. This simple example demonstrates an unsound drop:
```rust
struct Foo<'a> {
    val: &'a u32,
}

impl<'a> Drop for Foo<'a> {
    fn drop(&mut self) {
        println!("Dropping ref {}", self.val);
    }
}

fn main() {
    let a: u32 = 1;
    let foo = Foo { val: &a, };
    unsafe { unlinked(foo); }
}
```
There probably are more problems than this one.
Of course, given that unlinking is unsafe, we can just document the need for the programmer to assert all necessary preconditions for deferred destruction to be sound when calling `unlinked_drop`. AFAIK there are no intrinsics to verify anything more specific about the drop behaviour, so this might be the only thing we can do.
