### ISSUE TITLE
Ordering bug in SegQueue on the `high` location

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam#133]
<s>I think there is a subtle ordering bug in SegQueue's `try_pop`: https://github.com/crossbeam-rs/crossbeam/blob/master/src/sync/seg_queue.rs#L101

For the correctness, it is essential that `try_pop` reads the most recent value of `head.high`.  Otherwise, it may return `None` even if there are some remaining elements.

But the only write of `head.high` in `push` (https://github.com/crossbeam-rs/crossbeam/blob/master/src/sync/seg_queue.rs#L74), is not synchronized with the read in `try_pop`.  The write in `push` is released with `self.tail` and `*->next`, but the read in `try_pop` acquires only `self.head`.

I am thinking how to solve this issue.</s>

**Comment by jeehoonkang** [comment]
Never mind, I was confused.  Sorry for the false alarm.

It is totally OK for `try_pop` to see an old value of `head.high`.  Because, then we can righteously conclude that the queue is empty in the `try_pop`'s point of view.

**Comment by schets** [comment]
Actually, I think try_pop can be improved. It might not be necessary from a correctness perspective, but it's possible for the load of head.high to be ordered before the load of head.low. This means low can spuriously advance past high since elements can be pushed in between.

If the read to head was ordered after the load to low, you shouldn't be able to read a value of head lower than low and would be less likely to miss elements. In practice, the cost of the acquire load may be much higher than that of the rare spurious miss.

**Comment by jeehoonkang** [comment]
@schets I couldn't follow you..  Would you please elaborate the changes you are suggesting?

**Comment by schets** [comment]
Sorry, I mistyped head in some place where I meant head.high.

I realized the situation I describe isn't really a problem since it prevents a spurious CAS. Anyways, what can happen is: 
  1. Thread 1 reads head.high
  2. Multiple queue actions happen
  3. Thread 1 reads head.low, which has advanced

If head.high was loaded after head.low, then the loaded value of head.high would always be more up-to-date than the head.low value and there wouldn't be spurious misses of this form.
