### ISSUE TITLE
Queue lock implementation

### ISSUE THREAD

**Issue by sstewartgallus** [crossbeam-rs/crossbeam#136]
I recall that people previously have expressed interested in making a queue lock.

I have implemented an MCS queue lock see https://sstewartgallus.com/git?p=qlock.git;a=tree . It is about 1.5 times slower than the parking lot mutex but on the other hand is fair and I feel the code is much simpler.

The current API makes callers allocate nodes on the stack explicitly but it would be fairly simple to get and store these from a Treiber stack free list. The amount of nodes allocated would be proportional to the max number of blocked threads. Alternatively, the epoch API could be used for allocating nodes.

The current code aligns the lock to 64 bytes but if it was not so aligned would only become a single pointer which isn't that large in size costs.

The size of notifiers isn't an issue as these are either allocated on the stack or bounded by the max number of waiting threads.

If epoch GC was used then a CLH queue could be used which feels like it has some advantages to mean.

**Comment by stjepang** [comment]
`parking_lot` now has the ability to make locks fair: https://docs.rs/parking_lot/0.6.4/parking_lot/?search=fair

Is there currently any advantage of this lock over `parking_lot`?

**Comment by jeehoonkang** [comment]
Closing as I think this issue is out of scope; even if we need a queue lock that is different from what's provided in parking_lot, we should probably have it in parking_lot.

By the way, I believe this MCS lock (or something that used to be an MCS lock) to parking_lot's fair lock is spinlock to mutex.  If I understood correctly, this repo's lock spins and then `thread::yield()` in `fn lock()`; on the other hand, parking_lock's fair lock uses `thread::park()` and `thread::unpark()`.
