### ISSUE TITLE
Define clear scope for crossbeam

### ISSUE THREAD

**Issue by torkleyy** [crossbeam-rs/crossbeam#144]
Since there are other libraries for multi-threading itself (most notably rayon), it might be better to limit the scope of crossbeam to just concurrent data structures.

Btw, @ticki developed a concurrent hash map IIRC, I think it would also fit into this library.

**Comment by stjepang** [comment]
What in particular is currently present in Crossbeam that you think is out of its scope? Are you talking about scoped threads?

**Comment by torkleyy** [comment]
> Are you talking about scoped threads?

Yes.

**Comment by stjepang** [comment]
Please take a look at: https://github.com/crossbeam-rs/rfcs/pull/1
There is an effort to split the project into multiple crates, as well as expand in multiple directions.

On hash maps: Well, we definitely need one. `chashmap` is very interesting, but I'm concerned about contention - it basically wraps all operations around one `RwLock` (AFAIK). But otherwise looks pretty good! I'll start a discussion on hash tables in the RFCs repository soon.

Regarding the scoped threads API, this is probably a problem that needs a holistic approach - there are already many kinds of thread pools and we should probably unify them somehow. There was recently an interesting thread on this topic [here](https://internals.rust-lang.org/t/scoped-threads-in-the-nursery-maybe-with-rayon/4942).

@nikomatsakis What's your current opinion on the various thread-pool/spawn APIs? It seems there are three main approaches at the moment:

1. rayon-core: thread-pool with a work-stealing scheduler optimized for task parallelism
2. futures_cpupool: thread-pool with a scheduler optimized for fairness
3. crossbeam: very simple scoped threads

Are there any other similar abstractions we need? Can we unify these three somehow? I'd really like to see all three approaches implemented within the same crate.

**Comment by AlisdairO** [comment]
On the subject of a concurrent hash map, if you're at all interested you're welcome to fork/take over my concurrent-hash-map project. It's not lock free, but it is lock free on reads. I think that's at least as good as what's available in other rust concurrent hash maps right now.

Currently it's blocked on #13 , but other than that I believe it's functional.

**Comment by stjepang** [comment]
At this point Crossbeam's scope is hopefully clear enough so I'm closing the issue :)
