### ISSUE TITLE
Store a `Scope` in a struct

### ISSUE THREAD

**Issue by gbip** [crossbeam-rs/crossbeam#159]
Hello,
Is it possible to store a `Scope` in a struct ? The idea is to tie the lifetime of a thread to a struct instead of a function.
Thanks !

**Comment by Vtec234** [comment]
You could certainly store it within a struct, but that struct would also need to have a lifetime parameter, like `Scope<'a>` does. In general, the lifetime of a `Scope` has to be known statically and relies on the Rust lifetime rules for safety - if we know how long it lives, we know which objects can be used within that scope. This means that it cannot be arbitrarily extended in a dynamic manner, because then the Rust compiler wouldn't "know" whether the usage is safe.

**Comment by gbip** [comment]
Yes that is not a problem since the idea behind that is to avoid wrapping struct members in `Arc`s (for the `'static` lifetime) by borrowing them within the scope. So if we link the lifetime of the scope to the struct it borrows elements we should be good right ?
I don't know if this is clear, but it is the same idea as [this ](https://www.reddit.com/r/rust/comments/7iuzy8/thread_living_as_long_as_a_struct/)reddit post.
