### ISSUE TITLE
The scope should be sendable between threads

### ISSUE THREAD

**Issue by pedrocr** [crossbeam-rs/crossbeam#173]
Sometimes there is the need to have child threads of a crossbeam thread. It would be ideal if the scope could be passed around between threads to make that possible. Here's a minimal example of how that could be useful:

```rust
extern crate crossbeam;

struct MyStruct<'a> {
    scope: Option<&'a crossbeam::Scope<'a>>,
}

impl<'a> MyStruct<'a> {
    fn new() -> Self {
        Self {
            scope: None,
        }
    }
    
    fn set_scope(&mut self, scope: &'a crossbeam::Scope<'a>) {
        self.scope = Some(scope);
    }
    
    fn print(&self) {
        match self.scope {
            None => eprintln!("printed without scope"),
            Some(scope) => {
                scope.spawn(|| eprintln!("printed with scope"));
            },
        }
    }
}

fn main() {
    let s = MyStruct::new();

    crossbeam::scope(|scope| {
        s.set_scope(&scope);
    
        scope.spawn(|| {
            s.print();
        });
    });
}
```

**Comment by stjepang** [comment]
In addition to making `Scope` implement `Send` and `Sync` we should probably do the same for `ScopedJoinHandle`.

For comparison, `JoinHandle` implements these:
```rust
unsafe impl<T: Send> Send for JoinHandle<T> {}
unsafe impl<T: Sync> Sync for JoinHandle<T> {}
```

**Comment by stjepang** [comment]
@jeehoonkang 

> I guess it will invoke undefined behavior, but I'm not 100% sure. If it's the case, probably this problem is due to the fact that the API is not RAII-style...

The borrow checker will refuse that code anyway. Variable `s` has to be moved inside the scope.

Agreed on `Send` and `Sync`.

**Comment by stjepang** [comment]
I'm afraid making `Scope` implement `Sync` is basically useless because the borrow checker will still prevent it from being shared among threads.

Note that `&Scope` contains two lifetimes: `&'inner Scope<'outer>`. Lifetime `'inner` is variant (can be shrunk), while `'outer` is invariant (cannot be shrunk). Lifetime `'outer` outlives `'inner`.

Function `scope` introduces `'outer`. The signature of the function implies that `'outer` must be a lifetime that outlives closure `f`:

```rust
pub fn scope<'outer, F, R>(f: F) -> R
where
    F: FnOnce(&Scope<'outer>) -> R,
{
    // ...
}
```

In other words, lifetime `'outer` is at least as big as the scope. When spawning threads inside the scope, we can only capture variables that outlive `'outer`.

On the other hand, lifetime `'inner` is no bigger than the scope and refers to the internal data associated with the scope (e.g. list of spawned threads).

The problem arises when one tries nesting invocations of `Scope::spawn`:

```rust
crossbeam::scope(|scope| {
    scope.spawn(move || { // Thread (1)
        scope.spawn(move || { // Thread (2)
            // ...
        });
    });
});
```

This will not compile because thread (1) captures `scope` of type `&'inner Scope<'outer>`, which does not outlive `'outer`. So essentially it borrows data which is not outside the scope, thus violating the fundamental rule of scopes.

To work around the problem, we might introduce a special spawn method that provides the closure with a reference to the same scope as an argument:

```rust
crossbeam::scope(|scope| {
    scope.spawn_nested(|scope| { // Thread (1)
        scope.spawn(|| { // Thread (2)
            // ...
        });
    });
}
```

**Comment by stjepang** [comment]
Closing in favor of https://github.com/crossbeam-rs/crossbeam-utils/issues/46
