### ISSUE TITLE
Add Atomic Ring Buffer implementation

### ISSUE THREAD

**Issue by eun-ice** [crossbeam-rs/crossbeam#175]
msqueue is an excellent queue, but due to the fact that it is unbounded, requires mem allocations and has no way of querying the length it is not suitable for every use case.

Missing that I built [AtomicRingBuffer](https://github.com/eun-ice/atomicring) to complement the classes in crossbeam. 

If you want to add it to your library I would happily donate it to crossbeam.

**Comment by stjepang** [comment]
Hi @eun-ice, thank you for implementing this! Do you perhaps have any benchmark numbers?

I wonder how it fares against [this bounded queue](http://www.1024cores.net/home/lock-free-algorithms/queues/bounded-mpmc-queue), which should be one of the best similar queue implementations out there.

**Comment by eun-ice** [comment]
From reading the code, I think my implementation should be faster on 64 bit systems. Further, my implementation does not require an atomic per cell, so it's also more memory efficient.
Do you know of any Rust implementation for a direct benchmark?

**Comment by eun-ice** [comment]
Here is a more elaborate implementatino of the mentioned [bounded queue](https://github.com/mstump/queues/blob/master/include/mpmc-bounded-queue.hpp)
I'm not 100% sure, but I think on a concurrent write and read on an empty queue the reader basically does a spin wait until the write to the memory cell is completed. 
That should degrade if the memory cells are large or memory access is slow (e.g. due to paging) if the queue is mostly empty.

So without real world benchmarks and just by reading the code of MPMC I think my implementation has the following upsides:

- atomic-ring has lower memory overhead (mpmc requires an additional word per cell + two words instead of one for the counters)
- mpmc seems to do a spin wait on a concurrent write/read on an empty queue, atomic-ring does not need that, which is especially good if you store larger types
- mpmc implementation seems to fail after around size_t writes

Just to stress: This is from reading code and my conclusions might be wrong.

**Comment by stjepang** [comment]
I believe you can use [this implementation](https://docs.rs/mpmc/0.1.5/src/mpmc/lib.rs.html) for benchmarking - it's a pretty direct port from C++ to Rust. The only problem I see is that `struct State<T>` needs the `#[repr(C)]` attribute to ensure cache-efficient layout, but other than that it looks solid.

> atomic-ring has lower memory overhead (mpmc requires an additional word per cell + two words instead of one for the counters)

You're absolutely right about higher memory usage - that is probably the biggest downside. Out of curiosity, what's the largest queue size (in MBs) you've ever needed?

> mpmc seems to do a spin wait on a concurrent write/read on an empty queue, atomic-ring does not need that, which is especially good if you store larger types

Also true, but we need to see whether that matters at all. In theory, such spin waits should hopefully be rare or finish quickly.

> mpmc implementation seems to fail after around size_t writes

Not really. Perhaps the "fails on overflow" part seems to be implying so? It simply means that pushing into a full queue fails (rather than succeeding by overwriting the last element in the queue). Anyways, it's not a problem if head/tail indices overflow - no worries there.

A promising characteristic (in terms of performance) of Dmitry Vyukov's bounded MPMC queue is that it has separate indices for producers and consumers (head and tail). In other words, unless the queue is full or empty, producers and consumers won't contend by updating shared atomic values. This is in contrast to `atomicring`, where all operations contend on a single counter so the performance is limited by how fast the CPU can keep up with writing to a single atomic location from multiple threads.

**Comment by eun-ice** [comment]
Thank you for thinking deeply about my implementation.

> You're absolutely right about higher memory usage - that is probably the biggest downside. Out of curiosity, what's the largest queue size (in MBs) you've ever needed?`

I use lots and lots of queues for a highly concurrent network server, what I need is a ton of small queues for many network connections. These queues rarely have more than a few entries, but I need lots of them. So for me, memory overhead is an important issue.

>>mpmc implementation seems to fail after around size_t writes
> Not really. Perhaps the "fails on overflow" part seems to be implying so?

I thought it because pos + mask + 1 is stored in the cells sequence counter, which wraps around and, later this value is used for a comparison. Maybe I'm wrong, but I thought this would cause an issue after size_t writes, but even if it was the case this issue would be solvable.

> A promising characteristic (in terms of performance) of Dmitry Vyukov's bounded MPMC queue is that it has separate indices for producers and consumers (head and tail).

That is definitively an upside! But on the other hand, MPMC has to update the head/tail indices and also the sequences in the cell. I think which one is faster will definitively rely on the particular CPU used and workload.

My gut feeling is, that `atomicring` should perform about the same speed as Dmitry Vyukov MPMC. Exceptions are the concurrent write/read on an empty queue which should be slower on MPMC and the edge case with 255 pending write that cause `atomicring` to spin-wait.

**Comment by eun-ice** [comment]
Just a preliminary benchmark update, in single thread performance

```text
test bench_mpmc_singlethread_large ... bench:   1,582,313 ns/iter (+/- 139,426)
test bench_mpmc_singlethread_small ... bench:     234,185 ns/iter (+/- 17,750)
test bench_ring_singlethread_large ... bench:     866,560 ns/iter (+/- 63,566)
test bench_ring_singlethread_small ... bench:     353,543 ns/iter (+/- 36,572)

```
"large" is a Rust type with 512 bytes and "small" is a Rust type with just 8 bytes and the benchmark just does 10,000 push and 10,000 pops.

mpmc is significantly faster on the single-word type but significantly slower on a larger Rust type. I have no clue why and how to properly test multi-threaded performance outside our specific use case.

**Comment by stjepang** [comment]
You can try tweaking benchmarks in crossbeam-channel: https://github.com/crossbeam-rs/crossbeam-channel/tree/master/benchmarks

There are even benchmarks for `MsQueue` and `SegQueue` so it shouldn't be hard to add more for `mpmc` and `atomicring`. :)

**Comment by eun-ice** [comment]
I will check the benchmarks. 

For now I have [split the read/write indizes](https://github.com/eun-ice/atomicring) in two atomics, which relaxes some of the guarantees on .size() and .remaining_cap() and increases overhead to 5 words instead of 4. 

I was not able to measure any difference in performance but your logic that readers and writers won't update the same atomic was compelling. As a side effect the queue is dramatically better on systems with less than 64bit.

**Comment by eun-ice** [comment]
I added atomicring and mpmc to the benchmarks and created a PR https://github.com/crossbeam-rs/crossbeam-channel/pull/44

The results show that in this testcase, the  spinloop on 255 pending writes/reads does happen quite often, somewhat degrading the performance.

crossbeam-channel seems to be unbeatable :-)

![Benchmark results](https://imgur.com/a/xsh9DCP)

**Comment by eun-ice** [comment]
I don't know what size of type typically is used in a channel, the benchmark sends an i32 , which doesn't seem very realistic to me.

So I run the test again using a larger type, see https://github.com/eun-ice/crossbeam-channel/commit/c5abd51c6911af75b46a32ae265d4308bb8377dd

With this larger type ```atomicring``` is very competitive.


![plot](https://user-images.githubusercontent.com/17766811/39990048-ecd1a3e6-576b-11e8-8b75-e3f8f904658b.png)

**Comment by eun-ice** [comment]
I have pushed another benchmark with different sized messages.

Also, I added a naive waiting poll to ```atomicring``` called ```AtomicRingQueue``` using parking_lot's ```Condvar``` to better compare apples vs. apples. 

Here are the results:

![plot_large](https://user-images.githubusercontent.com/17766811/40011851-51f13e34-57a9-11e8-8ab4-4b028ce78fb6.png)
![plot_medium](https://user-images.githubusercontent.com/17766811/40011852-5209eec0-57a9-11e8-8def-b14901ebe1db.png)
![plot_small](https://user-images.githubusercontent.com/17766811/40011853-52240742-57a9-11e8-93f3-7c6343efb3db.png)

For larger types, AtomicRingQueue is even comparable to crossbeam-channel. Using the sophisticated notification mechanism of crossbeam-channel, I think AtomicRingBuffer has the chance of being a fast "Flavor" of crossbeam-channel.

**Comment by stjepang** [comment]
This is very interesting. Thank you so much for taking the time to do these extensive benchmarks!

`crossbeam-channel` is using the same kind of queue as `mpmc` for the bounded flavor (with extra memory barriers), so it's a little surprising that it's faster. Therefore, in theory, `mpmc` should actually always be as fast or faster than `crossbeam-channel`. My hypothesis is that `mpmc` is not using `thread::yield_now()` and `atomic::spin_loop_hint()` when spinning on a non-ready slot in the queue, which should explain the difference in performance.

It's also interesting how `atomicring` approaches the performance of `crossbeam-queue` (and even slightly surpasses!) as `size_of::<T>()` increases. My feeling is that, in the end, the `crossbeam-channel`/`mpmc` approach is still all-around preferred. And the reason why it's much faster when `size_of::<T>()` is small is because there is much less contention between producers and consumers. Please correct me if my reasoning is wrong. :)

I think the performance of `atomicring` could be greatly improved if you figure out how to split the shared atomic counter into two - one for producers and one for consumers. I'm not sure whether that's possible, though, but it'd be great if it is.

> I don't know what size of type typically is used in a channel, the benchmark sends an i32 , which doesn't seem very realistic to me.

That's a fair point. Sending an `i32` is not very realistic, but sending a `usize` (or `Box<T>`, `Arc<T>`, `Vec<T>`, which are similarly small types) is, though. Maybe we should switch from `i32` to `usize` in the benchmarks.

**Comment by eun-ice** [comment]
I have tried to find the reason why atomicring is slower than mpmc even going down to analyzing the resulting assembly code. I have split read and wrote atomic so that’s not an issue any more. 

It is something in the compare_and_exchange loop that makes the difference, from reading the assembly code atomicring should be about the same, but in reality it has 3times the overhead compared to mpmc. If you have any clue, I would be really thankful. 

Your channel is faster because the more efficient wait/notify algorithm, after all the fastest is a memory access that you don’t need to do at all ;)

I have designed atomicring just for passing data between threads, I use epoll for triggering the receiver anyways. In my use case atomicring is as fast as mpmc and has lower memory overhead. So I achieved my design goals, but I do agree that it is maybe not a good choice for small types if memory overhead is not an issue.

**Comment by eun-ice** [comment]
I had to fix a bug in ```plot.py```, I updated https://github.com/crossbeam-rs/crossbeam-channel/pull/45

It uses also I slightly optimized ```atomicring``` with a fastpath using only fetch_add

Here are the new charts:

Large Type ([usize ; 64])

![plot_large](https://user-images.githubusercontent.com/17766811/40104277-2fea2506-58f0-11e8-9b44-2e24696f6480.png)

Medium sized Type ([usize ; 32])

![plot_medium](https://user-images.githubusercontent.com/17766811/40104283-35a85490-58f0-11e8-814b-c0f19050b3e6.png)


Small Type ([usize ; 1])

![plot_small](https://user-images.githubusercontent.com/17766811/40104295-3a4eaaf8-58f0-11e8-8155-e1eced3ebb21.png)

**Comment by eun-ice** [comment]
I think we can close this issue. I thank you very much for all your input, you have helped me tremendously.
