### ISSUE TITLE
crossbeam 0.4 not found

### ISSUE THREAD

**Issue by gnzlbg** [crossbeam-rs/crossbeam#179]
The readme says:

> [dependencies]
> crossbeam = "0.4.0"

cargo answers:

> error: no matching version `^0.4.0` found for package `crossbeam`

**Comment by Vtec234** [comment]
Sorry, it's an oversight in the documentation. The latest version is `0.3.2`.

**Comment by jeehoonkang** [comment]
Probably it's good to publish `0.4.0` soon-ish.  Can we do that now?  What're the release blockers?

**Comment by stjepang** [comment]
Just a few simple requests before publishing `0.4.0`.

* Let's simplify the structure of `crossbeam-utils` a bit: https://github.com/crossbeam-rs/crossbeam-utils/pull/22
* `crossbeam-channel` is now basically stable and we can re-export it in `crossbeam`.
* Regarding re-exports, perhaps we should consider using `pub use` instead of `pub extern crate`, just like in Tokio (see [here](https://github.com/tokio-rs/tokio/blob/master/src/lib.rs)). This might lead to cleaner documentation.
