### ISSUE TITLE
Documentation link on crates.io gives HTTP 404

### ISSUE THREAD

**Issue by anderejd** [crossbeam-rs/crossbeam#181]

**Comment by jeehoonkang** [comment]
Documentation link is updated in `master`, but it's not uploaded to `crates.io` because we didn't publish `0.4.0`.  So I'm tempting to close this issue, but this issue is closed only after publishing `0.4.0`.  The `0.4.0` release will be tracked in #179.  I think it's best to publish as soon as possible..

Thanks for report!
