### ISSUE TITLE
Implement PartialEq + Eq for channel

### ISSUE THREAD

**Issue by Thomasdezeeuw** [crossbeam-rs/crossbeam#319]
As the title says, would it possible/acceptable to implement `PartialEq` and `Eq` for the channel types?

I'm wrapping a `Sender` in another type which I would like to implement `Eq` for. If approved I'll take a look at implementing it.

**Comment by Thomasdezeeuw** [comment]
To me to most logical would be if two `Senders` send to the same `Receiver` they should compare equal. For `Receiver` they are equal when the receive from the same queue.

In my use case I just want to know if two channels send to the same receiver. Alternatively this could be implemented as a method, something like `send_to_same_receiver(&self, other: &Self) -> bool`.

**Comment by Thomasdezeeuw** [comment]
I'm use channels to back communication between actors, using the actor model. And I would like to know whether or not I'm communication to the same actor given two (or more) channels.

**Comment by stjepang** [comment]
This sounds reasonable to me. In fact, previous versions of `crossbeam-channel` allowed comparisons between senders and receivers (even `s == r`), but then I removed comparisons in 0.3 with a conservative intention of adding them later in a possibly different form: https://docs.rs/crossbeam-channel/0.2.6/crossbeam_channel/struct.Sender.html

Golang allows comparing senders to senders and receivers to receivers, but cannot compare a sender to a receiver. I think we should follow suit and just add impls for sender-sender and receiver-receiver comparison.

**Comment by Thomasdezeeuw** [comment]
@stjepang Ok I'll try to send a pr today.

**Comment by Thomasdezeeuw** [comment]
I'm implemented it for all channels but the never flavour. It is implemented as

```rust
pub struct Channel<T> {
    _marker: PhantomData<T>,
}
```

So there is not a lot to compare... Want to make this a special case that always returns false?

**Comment by stjepang** [comment]
> So there is not a lot to compare... Want to make this a special case that always returns false?

Well, I suppose the following should work:

```rust
let r = never::<T>();
assert_eq!(r, r);
```

So by that logic, perhaps we should always return true?

**Comment by Thomasdezeeuw** [comment]
@stjepang but then `assert_eq!(never::<T>(), never::<T>());` is also true, which seems odd.

**Comment by stjepang** [comment]
@Thomasdezeeuw

How do you feel about implementing only `PartialEq`? If I can draw a parallel to floating point numbers, then `never` channels are sort of like `NaN` values and really should return `false` when compared to themselves?

**Comment by Thomasdezeeuw** [comment]
I'm ok with only implementing `PartialEq`. Should never channels then always return `false`, to match `NAN`?

```rust
 use std::f64::NAN;

fn main() {
    assert_eq!(0.0, 0.0);
    assert_ne!(0.0, NAN);
    assert_eq!(NAN, NAN); // fails.
}
```

([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f839161d0b2713229fa273e35fa63919))

**Comment by stjepang** [comment]
Yeah, that seems reasonable to me, although I'm not 100% sure so having another pair of eyes to look at this would be good. @BurntSushi Any thoughts on this?

**Comment by BurntSushi** [comment]
Personally, I still don't really understand why someone would want to compare channels, and I feel like I didn't really get a complete answer to that question.

Putting that aside, I'm not sure I understand why we can't make `never` channels comparable in the same way that non-never channels are comparable. I see above that the internal implementation is just a `PhantomData`, so that they may not be comparable in their current form, but what stops us from changing them so that they are comparable?

For example, I'd expect the following to pass:

```rust
let recv1 = never::<()>();
let recv2 = never::<()>();

assert_ne!(recv1, recv2);
assert_eq!(recv1, recv1.clone());
```

But the latter will not pass if "never" channels are given NaN semantics. In general, NaN represents a significant complication in the practical use of floating point numbers, so if we can avoid introducing NaN-like concepts elsewhere, then I think we should.

**Comment by Thomasdezeeuw** [comment]
@BurntSushi I agree that NaN semantics for comparing are complicated and I would like to avoid them as well. But how do you propose to change the never channel to make them comparable?

**Comment by stjepang** [comment]
@Thomasdezeeuw 

I suppose we could add a field to the `never` channel that distinguishes different instances:

```rust
pub struct Channel<T> {
    inner: AtomicCell<Option<Box<u8>>>,
    _marker: PhantomData<T>,
}
```

The `inner` field gets lazily initialized to `Some(Box::new(0u8))` on comparison. The address of the allocated byte can be used to compare channels.

**Comment by Thomasdezeeuw** [comment]
@stjepang allocating seems a high price to pay to me, but I don't see many better solutions. The only other thing I can think of is having a `static` counter to get unique ids for each never channel. But I don't have any benchmark numbers of allocating 1 byte vs increasing a shared, global counter.

**Comment by stjepang** [comment]
Never channels are only used to arbitrarily disable cases in `select!` so I doubt anyone is ever going to compare them. :)

**Comment by Thomasdezeeuw** [comment]
@stjepang Ok then I'll use your approach.

**Comment by Thomasdezeeuw** [comment]
@stjepang I've encountered a couple of problems with the design. Because the inner part is lazily set we need to set it when cloning. But since `Option<Box<u8>>` is not `Copy` we can't get the actual pointer from `AtomicCell`.

So instead I tried it with an `AtomicUsize` and a global counter, that is lazily set on clone (and only on clone). I think this can be done with `AtomicPtr` as well but that would get complicated with de-allocation.

**Comment by glaebhoerl** [comment]
Is there a practical problem with making all `never()` channels always compare `true`?

Intuitively one can imagine that there is only *one* "never channel" allocated somewhere behind the scenes, which `never()` merely returns a reference to.

**Comment by stjepang** [comment]
@glaebhoerl I agree, that was my first reaction to this problem too.

@Thomasdezeeuw, let's just return `true` when comparing `never()` channels? Do you find @glaebhoerl's argument convincing?

**Comment by Thomasdezeeuw** [comment]
@stjepang I'm fine with always returning true, @BurntSushi are you ok with that to?

**Comment by BurntSushi** [comment]
Without looking at concrete use cases (of which I've still seen none in any convincing detail for implementing `PartialEq` at all in the first place, and this request for more detail appears to continue to be ignored, but I'm not sure why), it's pretty hard to say. It certainly seems viable to say "all `never` channels are regarded as equivalent," but I could just as easily see someone being surprised by that in the future.

**Comment by Thomasdezeeuw** [comment]
@BurntSushi I've given my use case, I don't know how much more detail you want from that. Is fairly simple, there is one producer and multiple consumers can register themselves with the producer and I want to keep the list of consumers unique, thus I need to be able to compare channels (well senders).

I've made a note about comparing two never channels in the documentation of the `never` function, hopefully this prevents surprises but I do agree with your point.

**Comment by BurntSushi** [comment]
> Is fairly simple, there is one producer and multiple consumers can register themselves with the producer and I want to keep the list of consumers unique, thus I need to be able to compare channels (well senders).

Sure, but I don't see why that requires channel equality. It just seems weird to me to ascribe equality semantics to channels like this. For example, in your original comment, you said:

> I'm wrapping a `Sender` in another type which I would like to implement `Eq` for. If approved I'll take a look at implementing it.

But I don't think you need a channel to implement `Eq` for this. You can implement your own equality semantics with much the same way that channels would do it themselves internally.

> In my use case I just want to know if two channels send to the same receiver. Alternatively this could be implemented as a method, something like `send_to_same_receiver(&self, other: &Self) -> bool`.

I guess I would prefer this route instead of implementing `Eq`.

With all that said, reflecting on this, I don't think I feel that strongly. It just feels _weird_.

**Comment by glaebhoerl** [comment]
It's hard to intuit why another might find something weird when oneself does not, but let me try to reflect on why I don't find it weird -- equality for shared mutable objects in *many* languages is defined as address-equality: objects in general in Java/C#, `ref`s in ML, `IORef`s in Haskell, `std::shared_ptr`. (I wish I could cite Rust itself here! Niko has mentioned that he believes `Eq` for `Cell` being defined as contents-equality was a mistake, and I agree.)

Channels are but a slightly more sophisticated form of shared mutable object, so extending it to them only feels a short distance away. In general, for types which "have identity", the natural Eq impl is the one which tests if they are "the same one". (Incidentally, Haskell's `Chan` type also [has this](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Concurrent-Chan.html); I haven't checked other languages.) Maybe the thing which throws one for a loop here is the `Sender`/`Receiver` split, so that the identity being compared is actually that of the internal queue, which is hidden?

**Comment by BurntSushi** [comment]
@glaebhoerl Thanks for that perspective. I think that might assuage my feeling a bit. I think I actually find address-equality itself to be strange, where contents-equality makes a lot more sense to me. (For example, I'm having trouble understanding the perspective that `Eq` on `Cell` shouldn't be defined as contents-equality.) So in that respect, it makes sense why I'm finding `Eq` on channels to be weird.

This also reminds me of what my initial reaction to this issue was: I would have thought equality between two channels to mean something like, "at that specific moment in time, the internal queue of both channels contain the same elements." That's why my first question was asking what "equality" on channels actually means. In retrospect, address-equality makes a lot more sense, but you don't actually see a lot of that in Rust (and I've been under the impression that that's a good thing), which is maybe why it feels so weird to me.

**Comment by glaebhoerl** [comment]
I think the intuition there is that `==` should always be a "pure function" -- it shouldn't ever touch shared mutable state. (An address is just a value, and `==` on it will always give the same result; the contents at that address are s.m.s., and then `==` will give different results depending on when you ask.) A truly egregious example of this being violated is Java's `URL.equals()` actually [doing a DNS lookup](http://blog.markfeeney.com/2010/11/java-uri-vs-url.html) to determine if the hosts resolve to the same IP address! Now that one's obviously and flagrantly "Wrong", but it's a similar flavor of wrong, just more extreme. In Haskell the type of `==` prevents it from accessing shared mutable state ("`IO`"), so address-equality is the only possible choice.

> but you don't actually see a lot of that in Rust (and I've been under the impression that that's a good thing)

It generally is; using address-equality to distinguish normal data that *isn't* shared-mutable is *also* a flavor of wrong, and Rust does well to avoid it (though it could've been stronger about it by making cast-to-raw-ptr `unsafe`).

(I'm *trying* to explain it other than by pointing to, "Haskell does it this way, therefore it is right", and feel like I'm mostly failing. Oh well, better than nothing hopefully...)

**Comment by BurntSushi** [comment]
@glaebhoerl Thanks for the explanation. It definitely helps. I'll keep noodling on it.

In any case, for this particular issue, I don't strongly object to the current course. (Implementing Eq using address equality and considering all `never` channels equivalent.)

**Comment by stjepang** [comment]
Another possibility is to do something similar to [`ThreadId`](https://doc.rust-lang.org/nightly/std/thread/struct.Thread.html#method.id):

```rust
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ChannelId(usize);

impl<T> Receiver<T> {
    pub fn id(&self) -> ChannelId;
}

impl<T> Sender<T> {
    pub fn id(&self) -> ChannelId;
}
```

The ID would internally be just a `usize`, a unique identifier for the channel of this particular type. All heap-allocated channels would be identified by the pointer address, while the "never" channels would be identified by 0.

**Comment by Thomasdezeeuw** [comment]
@BurntSushi, @glaebhoerl Thanks for the discussion, I now understand both points of view.

I think we have three possible APIs:
- `PartialEq`,
- special method, and
- `ChannelId`

```rust
// PartialEq, Eq.
sender1 == sender2;

// Special method, modelled after `LocalWaker::will_wake`.
sender1.will_send_to(&sender2);
sender1.same_channel(&sender2);
// Or an alternative method name.

// ChannelId, modelled after `ThreadId`.
sender1.id() == sender2.id();
// Bonus of `ChannelId` is that we can compare senders with receivers (I think).
sender1.id() == receiver2.id();
```

**Comment by Thomasdezeeuw** [comment]
@stjepang Do you have any ideas for future API for `ChannelId`?

Also have you thought about the lifetime of `ChanneldId`? Since the inner `usize` comes from a pointer, the pointer can be reused resulting in false positives.

**Comment by stjepang** [comment]
@Thomasdezeeuw Thanks for the overview of all the options!

> Do you have any ideas for future API for `ChannelId`?

I don't have in mind anything beside what was sketched out in my last comment - that's pretty much it.

> Also have you thought about the lifetime of `ChanneldId`? Since the inner `usize` comes from a pointer, the pointer can be reused resulting in false positives.

Well, just like with `ThreadId`, the identifier is something that is valid only while the channel is alive. The moment the channel is destroyed, the ID becomes meaningless and might indeed produce false positives.

You're making a fair point, but we shouldn't fret over the issue, I think. If IDs work well for threads, they should work for channels too...

**Comment by Thomasdezeeuw** [comment]
So I think there are three questions left to answer:

- What is the best API to "determine whether two senders send to the same receiver"?
- Same as above but then for receivers.
- Should the API support determining if a sender is sending to a receiver?

Any thoughts?

**Comment by Thomasdezeeuw** [comment]
> > Also have you thought about the lifetime of `ChanneldId`? Since the inner `usize` comes from a pointer, the pointer can be reused resulting in false positives.
> 
> Well, just like with `ThreadId`, the identifier is something that is valid only while the channel is alive. The moment the channel is destroyed, the ID becomes meaningless and might indeed produce false positives.
> 
> You're making a fair point, but we shouldn't fret over the issue, I think. If IDs work well for threads, they should work for channels too...

@stjepang  I don't know too much about the "uniqueness" of `ThreadId`, however memory address can easily be reused. I don't want to following code to fail, but in a single threaded application it could with an allocator that reuses memory addresses.

```rust
let (s, _) = unbounded();
let id1 = s.id();
drop(s);
let (s, _) = unbounded();
let id2 = s.id();
asser_ne!(id1, id2);
```

**Comment by Thomasdezeeuw** [comment]
@BurntSushi, @glaebhoerl, @stjepang it's been two weeks, any preferences in the API possibilities I proposed in https://github.com/crossbeam-rs/crossbeam/issues/319#issuecomment-462388472?

**Comment by BurntSushi** [comment]
I think I personally like the explicit method, e.g., `same_channel`. The intended semantics are IMO clearer. But I honestly don't have a super strong preference here. I think @glaebhoerl somewhat assuaged me of my concerns here.

**Comment by stjepang** [comment]
I like the `same_channel` idea too. If I may draw another parallel, it also reminds me of `Arc::ptr_eq`.

Not 100% sure if I'm sold on the `same_channel` name yet, but we can throw a few ideas around and pick one. Here are some more: `same_sender`, `sender_eq`, `eq_sender`, `channel_eq`.

**Comment by Thomasdezeeuw** [comment]
Some ideas

```rust
sender1.sends_to(&sender2);

// Special method, modelled after `LocalWaker::will_wake`.
sender1.will_send_to(&sender2);
sender1.same_channel(&sender2);
// Or an alternative method name.
```

**Comment by Thomasdezeeuw** [comment]
(Ignore my previous, now deleted comment.)

Some ideas.

```rust
sender1.same_sender(&sender2);
sender1.same_receiver(&sender2);
sender1.same_channel(&sender2);
sender1.same_target(&sender2);
sender1.sender_eq(&sender2);
sender1.eq_sender(&sender2);
sender1.channel_eq(&sender2);
```

And for senders and receiver, if we want that.

```rust
sender.sends_to(&receiver);
sender.will_send_to(&receiver);
```

I think my preference goes to `sender1.same_receiver(&sender2)`.

**Comment by Thomasdezeeuw** [comment]
I've updates #320 to use `same_channel`.

**Comment by Thomasdezeeuw** [comment]
Thanks everybody for the reviews and discussions.

**Comment by Pauan** [comment]
@BurntSushi There is a long and somewhat dense article (from 1993!) that goes into a lot of detail about this (and gives many examples of *why* their equality is correct):

http://home.pipeline.com/~hbaker1/ObjectIdentity.html

It lists these three requirements for equality:

1. objects retain their identity throughout their lifetime--identity is constant and immutable;
2. object identity is preserved by the basic value-transmission operations of the programming language--binding, argument-passing, value-returning, and assignment;
3. objects with the same identity are operationally equivalent.

Basically, if two objects are equal, they should remain equal. And moving objects around (e.g. putting them into data structures) shouldn't change their equality.

That's really important in practice!

For example, `BTreeMap` has a requirement that sorting is stable. If you violate that, then your impl of `Ord` is wrong.

Similarly, `HashMap` has a [requirement that `Eq` and `Hash` are pure](https://doc.rust-lang.org/nightly/std/collections/struct.HashMap.html):

> It is a logic error for a key to be modified in such a way that the key's hash, as determined by the Hash trait, or its equality, as determined by the Eq trait, changes while it is in the map. This is normally only possible through Cell, RefCell, global state, I/O, or unsafe code.

Note that it specifically calls out `Cell` and `RefCell`, because their equality isn't pure!

If `Cell` and `RefCell` compared equality by reference, then they would work perfectly fine with `HashMap`. But because they compare by value, now they can break if you use them as a key in a `HashMap`.

So the basic principle is: immutable things should always compare by value. Mutable things should always compare by reference.

This guarantees that equality is well behaved under every circumstance (including when using `HashMap`/`BTreeMap`, but also in other situations too).

Some languages (like Haskell) do that correctly. Most languages (including Rust) get it wrong, so they end up with equality bugs (like using `Cell` in a `HashMap`).

**Comment by BurntSushi** [comment]
> Some languages (like Haskell) do that correctly. Most languages (including Rust) get it wrong, so they end up with equality bugs (like using Cell in a HashMap).

Happy to be wrong if it means this program always prints `true`:

```rust
fn main() {
    let x = "foo".to_string();
    let y = "foo".to_string();
    println!("{:?}", x == y);
}
```
