### ISSUE TITLE
Resolve leak of participant data

### ISSUE THREAD

**Issue by aturon** [crossbeam-rs/crossbeam#37]
As of https://github.com/aturon/crossbeam/pull/42, participant data is leaked on thread exit. We need to figure out a workable algorithm for reclaiming inactive participants.

**Comment by aturon** [comment]
@msullivan BTW, the tweak to the participant reclamation scheme didn't work out -- the scheme as a whole is busted (see linked PR). I'll try to roll out something new soon.

**Comment by msullivan** [comment]
How bad would it be to just use an rwlock around the participants list? It technically ruins being lock-free (or, if you do a trylock, could allow memory reclamation to be delayed indefinitely), but the write-lock would only be taken on thread creation/deletion, so I would guess it's not likely to be a big problem in practice?

**Comment by aturon** [comment]
@msullivan It's a reasonable fallback option, and perhaps a better choice than the leakage we have today. In the long run, though, a lock-free approach should be possible and (I think) strictly superior.

**Comment by schets** [comment]
What if enrolling nodes walked the participant list, or at least a bounded portion of it, to see if they could re-use a node marked as inactive before adding a new entry? Now, it appears as if [a new entry is created for every thread that enters the epoch](https://github.com/aturon/crossbeam/blob/master/src/mem/epoch/participants.rs#L60). This would reduce the magnitude of the leak to be something closer to the maximum number of concurrently enrolled threads.

I don't immediately see a reason old participant shouldn't be able to get 'restarted' by a new thread. This wouldn't completely remove the leak, but makes a lot of the pathological scenarios less likely.

**Comment by aturon** [comment]
@schets Not a bad idea! Limiting to the high water mark in number of concurrent threads is likely good enough.

(Still, I believe in the long run we ought to be able to do this with a simple lock-free structure, just one a bit more clever :-)

**Comment by schets** [comment]
Something else I just though of - maybe only one thread should be able to actually delete from the list, and other threads traversing/adding to the list simply don't delete? I don't know what the exact nature of the segfault was, but it making it a single-writer list (or at least, single writer for deletions from the middle) seems fairly simple.

**Comment by msullivan** [comment]
One approach to removing an /individual/ node from a list is to do the broken removal algorithm (search for it, disconnect it with CAS; broken because it might disconnect the node from an already disconnected section) but iterate it until the node isn't found in the list.

Then there are a variety of different schemes that could be used to trigger searching for and unlinking a node.

**Comment by schets** [comment]
I have an experimental rough draft of the single-writer deletion up [here], but it segfaults occasionally. It's hard to repro by hand so I'm having a hard time valgrinding it, but if anyone wants to take a look here it is.

I'm worried that a scheme without pruning the list will make GC's take very, very long as they traverse bigger lists. The node reclamation scheme I mentioned makes any sort of unlinking impossible, where as not freeing anything at all maybe you could just manipulate pointers so that inactive nodes aren't traversed but aren't freed either.

**Comment by msullivan** [comment]
I've got what I think is a working implementation of lazy Participant reclamation in my C++ port: https://github.com/msullivan/rmc-compiler/blob/master/examples/case_studies/epoch_sc.cpp#L75-L106.

It uses the low bit of the next pointers to encode whether a node is active. (I got the general sketch of this from http://www.research.ibm.com/people/m/michael/spaa-2002.pdf.)

I'm trying to decide what the best way is to abuse the low bits of pointers in Rust is.

**Comment by aturon** [comment]
Hey @msullivan -- funny enough, I currently have a crossbeam branch doing exactly this (using marked pointers), as well as a couple of other things. I'm doing it via a generic `LinkedList<T>` type that can also be used as the basis for a skip list, etc.

In my implementation, I ended up introducing a `MarkedAtomic` type that uses the low bit for a marker.

I'm hoping to have something up on Friday, maybe we can compare notes at that point?
