### ISSUE TITLE
How scoped threads work: the role of the borrow checker

### ISSUE THREAD

**Issue by schomatis** [crossbeam-rs/crossbeam#385]
`crossbeam-utils` `docs` `question`

(Rust newbie asking.) Trying to better understand the difference between `crossbeam` and `std` threads I found the explanation

https://github.com/crossbeam-rs/crossbeam/blob/8cc906b9933ef443331c30513026346399debd2d/crossbeam-utils/src/thread.rs#L78-L79

in which I don't quite follow _how_ that guarantee is enforced. I was under the impression that the interaction with the borrow checker happened in a conversion to the `'static` lifetime of the `closure` the thread will execute

https://github.com/crossbeam-rs/crossbeam/blob/8cc906b9933ef443331c30513026346399debd2d/crossbeam-utils/src/thread.rs#L426-L427

but I don't understand (and possible I'm misinterpreting the documentation) if the borrow checker is actually enforcing the limited scope of the thread or if this is something just guaranteed by the API, meaning I can remove the logic that joins the threads at the end of the `scope()`

https://github.com/crossbeam-rs/crossbeam/blob/8cc906b9933ef443331c30513026346399debd2d/crossbeam-utils/src/thread.rs#L171-L176

and the program will still build successfully (the tests will fail of course, but the compiler, and particularly the borrow checker, won't complain).

(Just to clarify, I'm not saying the mechanism is incorrect or that it doesn't work, this is just a question from an inexperienced Rust, and Crossbeam, developer trying to better understand how the system works; if there is anything worth clarifying in the documentation I'll happily submit a PR about it).

**Comment by stjepang** [comment]
> but I don't understand (and possible I'm misinterpreting the documentation) if the borrow checker is actually enforcing the limited scope of the thread or if this is something just guaranteed by the API

Borrow checking is just a part of type checking. Lifetimes are actually types and therefore all the borrow checker does is it verifies that all the types/lifetimes match as expected.

Crossbeam's scoped threads are a new abstraction built with unsafe code, where it is allowed to transmute types and lifetimes into other arbitrary types and lifetimes. And as long as the public API is sound, everything is all right.

> and the program will still build successfully (the tests will fail of course, but the compiler, and particularly the borrow checker, won't complain).

But then the scoped threads would be unsound, i.e. broken :) The idea is that we build an API for scoped threads that can't be misused from the outside.

The reason why you're able to delete this code and still make it compile is because there's other unsafe code within the implementation of scoped threads that makes this possible. But that doesn't mean deleting this code is a safe thing to do!

**Comment by schomatis** [comment]
Hey @stjepang, thanks for the detailed answer. I understand and agree with everything you say, the point I was trying to make was targeted towards the documentation (a label I would add to this issue), where the phrase _we guarantee to the borrow checker_ might give the impression that the borrow checker is actually the one verifying that the thread is indeed scoped, which from your previous comment I understand it doesn't.

It seems that that is the responsibility of the Crossbeam API, which is taking charge and "disabling" the lifetime check using a conversion to `'static` and applying other checks itself. This is a subtle and unimportant distinction, I'm just mentioning it because it may help inexperienced Rust developers (as myself) to better distinguish the boundaries between what is the Rust compiler able to do and what is Crossbeam adding on top of it.
