### ISSUE TITLE
New release of crossbeam-epoch

### ISSUE THREAD

**Issue by Aaron1011** [crossbeam-rs/crossbeam#401]
The current unreleased version of `crossbeam-epoch` bumps its `scopeguard` dependency for `1.0`. This will be a big help in reducing duplicate `scopeguard` dependencies - since it's now at `1.0`, Cargo will apply the normal Semver rules when picking dependencies (i.e. treating minor versions as compatible).

It would be very useful to get a new point release of `crossbeam-epoch` to make this transitive dependency change available.

**Comment by kingishb** [comment]
Hi! This is also necessary to get a new version of `memoffset`, which was upgraded in https://github.com/crossbeam-rs/crossbeam/pull/402 but did not have a corresponding hotfix change to the parent project.  My local version of crossbeam  `0.7.1` , for example, doesn't update the dependency, which the [cargo audit](https://github.com/RustSec/cargo-audit) tool flags as a having security vulnerability.

```
error: Vulnerable crates found!

ID:      RUSTSEC-2019-0011
Crate:   memoffset
Version: 0.2.1
Date:    2019-07-16
URL:     https://github.com/Gilnaa/memoffset/issues/9#issuecomment-505461490
Title:   Flaw in offset_of and span_of causes SIGILL, potential memory unsafety
Solution: upgrade to: >= 0.5.0

error: 1 vulnerability found!
```

**Comment by kingishb** [comment]
Oh whoops, I see this is already happening in the linked discussion. Sorry to be repetitive -- thanks!

**Comment by kingishb** [comment]
Hey just to follow up in both threads I wrote up what I see here: https://github.com/RustSec/advisory-db/pull/124#issuecomment-512870145

**Comment by rfk** [comment]
> Version 0.2.1 is unsound but not known to cause any concrete problems.

Just an FYI for anyone who comes across this issue, the advisory has since been updated to include all versions prior to 0.5, so 0.2.1 is indeed affected and will be reported y `cargo audit`.  Ref https://github.com/RustSec/advisory-db/pull/129

**Comment by RalfJung** [comment]
Right, it was found out that the lack of protection against deref coercions could (if the deref coercion panics) lead to `drop` on uninitialized memory.

However, if crossbeam does not actually call `offset_of` on a field involving a deref coercion, there is no issue in crossbeam.

**Comment by jimmycuadra** [comment]
Any updates on a new release to crates.io? The memoffset issue is causing any project that runs cargo-audit during CI to fail builds.

**Comment by dekellum** [comment]
Will the next release be a PATCH-compatible, crossbeam-epoch-0.7.2? That would be nice because the security fix for memoffset 0.5, per 7169d4f, would most likely get applied downstream via `cargo update`? (Reading this I see that that security issue might be overstated, but still nice to move forward with memoffset 0.5)

Or does it require new MINOR releases, e.g: (crossbeam-epoch-0.8.0 crosbeam-0.8.0 crossbeam-deque-0.8.0 …)?  Below are the changes since the crossbeam-epoch-0.7.1 release. The MSRV bump was reverted.  Looks like scopeguard (upgraded in b465caa0, #370) is a purely private dependency? At first glance, 088012e appears to change pub interface, but `IsElement<T>` isn't actually exported?

If this does need a MINOR release, would it be worth considering backporting only the security fix(s) or other PATCH-safe changes to a crossbeam-epoch-0.7.2?  I'm happy to try and help, if I can.

``` bash
% git log crossbeam-epoch-0.7.1.. -- crossbeam-epoch
```

7169d4f update memoffset to 0.5, which contains plenty of soundness fixes
088012e Fix list's finalize API
32ef2fd Small fixes and renames
9d5346c Remove unnecessary mention of Box
dd6212a Update readmes
96ddd4d Support non-atomic targets
cafe143 Add the alloc feature
7b6cca7 Fix no_std build
0e266b0 Revert "Bump the minimum Rust version"
aa1b263 epoch: Add Atomic::into_owned
b4651ca chore: Update scopeguard to 1
b5f287d Bump the minimum Rust version
a1e480c Merge #357
72fbfbe Update README.md
de696d5 Add copyright notice
c92c4f5 Merge #355
28da96f Fix broken build on latest nightly
e62a39f long-form superscript notation in readmes
8c20ae9 Add minimal versions check to travis
2076c5a Rustfmt everything

**Comment by stjepang** [comment]
I have just published a new version of `crossbeam-epoch`. Sorry for the delay!

**Comment by RalfJung** [comment]
Thanks a lot @stjepang !
