### ISSUE TITLE
drop method not called

### ISSUE THREAD

**Issue by gabriel-araujjo** [crossbeam-rs/crossbeam#538]
Why the `drop` method is not called on the following snippet when `Foo` is wrapped inside a `crossbeam_epoch::Atomic`.

```rust
use crossbeam_epoch::Atomic;
use std::ops::Drop;
use std::sync::atomic::Ordering::SeqCst;

#[derive(Debug)]
struct Foo {
    f: u32,
}

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Dropping {}", self.f);
    }
}

fn main() {
    let x = Foo { f: 33 };
    let a = Atomic::new(Foo { f: 22 });
    let guard = &crossbeam_epoch::pin();
    let p = a.load(SeqCst, guard);
    println!("{:?}, {:?}", unsafe { p.deref() }, x);
}

// Output:
// -------
// Foo { f: 22 }, Foo { f: 33 }
// Dropping 33

```
Am I making some mistake? Should I explicitly call `p.deref().drop()`?

**Comment by taiki-e** [comment]
Sorry for the delayed response. `Atomic` does not drop the pointee intentional. For the way to drop the pointee of `Atomic`, see examples of [`Atomic::into_owned`](https://docs.rs/crossbeam-epoch/0.9.0/crossbeam_epoch/struct.Atomic.html#method.into_owned), [`Shared::into_owned`](https://docs.rs/crossbeam-epoch/0.9.0/crossbeam_epoch/struct.Shared.html#method.into_owned), [`Guard::defer_destroy`](https://docs.rs/crossbeam-epoch/0.9.0/crossbeam_epoch/struct.Guard.html#method.defer_destroy), [`unprotected`](https://docs.rs/crossbeam-epoch/0.9.0/crossbeam_epoch/fn.unprotected.html), etc.

https://docs.rs/crossbeam-epoch/0.9.0/crossbeam_epoch/epoch/struct.Atomic.html#method.into_owned
> This consumes the atomic and converts it into Owned. As Atomic doesn't have a destructor and doesn't drop the pointee while Owned does, this is suitable for destructors of data structures.
