### ISSUE TITLE
Can AtomicCell support to load by cloning if the T can be cloned but not copied?

### ISSUE THREAD

**Issue by bachue** [crossbeam-rs/crossbeam#593]
I stored a struct into AtomicCell, which can be cloned but not be copied. Can I load it from AtomicCell by cloning, or can I just get the reference of it and I can do cloning by myself? Thanks

**Comment by taiki-e** [comment]
It may be possible to implement it if specialization is stable, but it cannot be lock-free because non-Copy types cannot be represented as atomic types of the standard library.
There are also issues related to destructors and interior mutability. See https://users.rust-lang.org/t/why-does-cell-require-copy-instead-of-clone/5769 for more.

In any case, I don't think it's very useful because non-lock-free AtomicCell is actually similar to using a mutex.
