### ISSUE TITLE
crossbeam-utils atomic::seq_lock::tests::test_abort unit test fails on 32-bit architectures

### ISSUE THREAD

**Issue by decathorpe** [crossbeam-rs/crossbeam#595]
From the test output:

```
test atomic::seq_lock::tests::test_abort ... FAILED
failures:
---- atomic::seq_lock::tests::test_abort stdout ----
thread 'atomic::seq_lock::tests::test_abort' panicked at 'assertion failed: `(left == right)`
  left: `(0, 0)`,
 right: `(0, 2)`: aborted write does not update the stamp', src/atomic/seq_lock_wide.rs:151:9
```

The same failure occurs on both i686 and armv7hl, on fedora rawhide. Running the tests on 64-bit architectures is fine.

Can I ignore this test failure for now or is it indicative of a real problem?

**Comment by jeehoonkang** [comment]
~~I think it's indicative of a real problem.  But I cannot understand why this happens, even though `test_abort()` is relatively easy because it's completely sequential without concurrency...~~

I wonder if inserting the following line between L112 and L113 works for your test environment (https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-utils/src/atomic/seq_lock_wide.rs#L112-L113):

```
mem::forget(self);
```

I'm suspecting that the write guard is wrongly dropped in `abort()`.
