### ISSUE TITLE
Add thread-pool capabilities to scope

### ISSUE THREAD

**Issue by TyOverby** [crossbeam-rs/crossbeam#64]
Maybe with an API like 

``` rust
let pool = Pool::new(8); // 8 threads in the pool.
pool.scoped(|scope| {
    scope.spawn(...);
});
```

**Comment by bfrog** [comment]
+1

**Comment by upsuper** [comment]
It would probably also be useful to allow user to control which task goes to which thread, for example, something like
```rust
let pool = Pool::new(8);
pool.scoped(|threads| {
    for (thread, task) in threads.iter().zip(tasks.iter()) {
        thread.dispatch(task);
    }
});
```

**Comment by upsuper** [comment]
One use case of thread pool can be seen in [bryant/argon2rs](https://github.com/bryant/argon2rs), where fixed number of threads need to be synchronized frequently, which isn't quite doable with crossbeam right now.

**Comment by jeehoonkang** [comment]
FYI, probably this is one of the most relevant crates to this issue: https://github.com/Kimundi/scoped-threadpool-rs . Also there is a discussion on various Rust libraries on cpu pools: https://github.com/rust-lang-nursery/futures-rs/issues/411

**Comment by jeehoonkang** [comment]
Also related: https://docs.rs/rayon/0.9.0/rayon/fn.scope.html .  At least, we need to write a better documentation as done in Rayon.

**Comment by stjepang** [comment]
The library ecosystem has evolved quite a bit since this question was asked. Tokio is now the thread pool for async IO and Rayon is the thread pool for parallel CPU-intensive tasks.

Since we already have two universal thread pools that cover a wide range of use cases, I don't see a need for creating another one. Even if neither Tokio nor Rayon are good enough for a particular use case, then a simple thread pool provided by Crossbeam probably won't be either.

Should we close this issue?

**Comment by nhukc** [comment]
I don't think this is resolved. 

Rayon does not work for cases where a mutex is required due to work stealing. A non-work-stealing scoped thread pool implementation would be extremely useful for writing userspace rust drivers.

See https://github.com/rayon-rs/rayon/issues/1174 for additional details.
