### ISSUE TITLE
ArrayQueue: is it possible to push and pop and the same time?

### ISSUE THREAD

**Issue by gootorov** [crossbeam-rs/crossbeam#680]
Essentially I'm looking for something like this:

```Rust
use crossbeam_queue::ArrayQueue;

// allow a maximum of two elements.
let q = ArrayQueue::new(2);

assert_eq!(q.push_displacing(10), None);
assert_eq!(q.push_displacing(20), None);
assert_eq!(q.push_displacing(30), Some(10));
```
(not sure on the naming)

Is it possible to implement something like this in theory? (I guess it would require writing to two memory locations atomically at the same time, which there is no way to so, not sure)
If, however, it is possible, I'd be happy to open a PR given some hints how to properly implement it!

**Comment by Bajix** [comment]
I think that's not possible because AVX/AVX2 isn't formally guaranteed to be atomic and so this would only be viable on certain chipsets and would probably resort to inline assembly or unsafely using multiple mut references w/ something like [packed_simd_2](https://docs.rs/packed_simd_2) and just praying it works. I wouldn't expect this to ever be supported

**Comment by brunocodutra** [comment]
We could in fact change the RingQueue I propose in #789 to return the oldest element instead of dropping it in place. Seems like a great idea to me in fact, I'll look into that hopefully later today.
