### ISSUE TITLE
Does this repo support “Distributed Epoch Based Reclamation”？

### ISSUE THREAD

**Issue by devillove084** [crossbeam-rs/crossbeam#685]
I want to use this repo for the distributed system. Can i use this repo?

**Comment by jeehoonkang** [comment]
Currently, crossbeam supports only a single system. Support for distributed systems, if it will be implemented, will require huge design work, I think. Maybe we can continue to discuss it in the RFC repo: https://github.com/crossbeam-rs/rfcs.

For now, I'd like to close this issue because I cannot think of concrete action items...
