### ISSUE TITLE
Feature Request: peek head for *Queue

### ISSUE THREAD

**Issue by alexandermerritt** [crossbeam-rs/crossbeam#73]
How possible would it be to peek at the front item of the queue without removing it?

**Comment by sorear** [comment]
It would have to be an opt-in function.  Right now, if thread A successfully removes a node from a queue, thread A *immediately* has *exclusive* access to the removed item (return by owned value); if thread B could peek the queue, then thread B could have a reference to the item and thread A could not receive exclusive ownership.

Presumably, you'd have to have the values in the queue be something that implements `Clone`, presumably `Arc<T>`, so that the queue could return references to both thread A and thread B.  (Thread B *might* be able to get a borrow that has the same lifetime as a pin, but this does not work nearly as well for thread A.)  Then you'd have to have the queue owning values and dropping the reference / deleting them *itself* when the RCU grace period ends; this is precisely the thought process that lead to…

See #13.

**Comment by stjepang** [comment]
Like @sorear said, peeking the head is a difficult operation to support without significantly affecting the overall performance, so we're unlikely to add it.

@alexandermerritt Elaborating on *why* you want to be able to peak the head would help (what is your use case). Perhaps there are other ways of solving the problem.

**Comment by stjepang** [comment]
We almost surely won't implement this. Closing the issue.

Maybe we could add a different queue that is slower than `MsQueue`/`SegQueue` while supporting the peek operation, but I'm not sure how useful such a data structure would be. If you do need it, let us know!

**Comment by aembke** [comment]
A bit of context for a possible use case where this would be useful for me at the moment:

I’d like to use `SegQueue` to improve a pipelining implementation in a redis client. The network layer uses [split](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.into_split) such that the `Stream` portion of the socket is read via a recv loop in one task while writes happen in another task. These tasks share a queue of in-flight commands in order to associate responses with requests. 

One of the potential failure modes I’m concerned about is connections silently going unresponsive without closing. This is a particularly annoying failure mode, especially in Docker via `docker pause`, because the socket doesn’t receive any indication of an issue and writes often continue to work. To detect this I’m using another task that periodically checks the response latency of the oldest frame (at the front of the shared queue). However, I don’t want to remove this frame from the queue unless the response latency exceeds some threshold. The response latency is calculated via a `written: Instant` field on each frame in the queue. 

In this scenario I don’t need `peek` to return a reference back from the queue, but rather just the `written` value, which in this case happens to be an `Instant`. Would something like this be more feasible since it avoids handing out references?


```
struct SegQueue<T> { 

 // …

  pub fn peek<V>(&self, func: F) -> Option<V> where F: FnOnce(&T) -> Option<V> {
    // …
  }

}

struct Command {
  // …
  written: Instant
}

fn example() {
  let queue = SegQueue::new();
  // …

  if let Some(written) = queue.peek(|command| command.written) {
    // …
  }
}
```

I’m guessing there would need to some further restrictions on `V` here, but that’s the general idea.

**Comment by taiki-e** [comment]
AFAIK, there are three main ways to implement this.

- Create a new queue that uses GC or something similar. This supports peeking from multiple threads, but is slow.
- Add a method that takes a mutable reference. Peeking from multiple threads is not supported.
- Add an mpsc variant or add an unsafe method that has the same requirement. The consumer is free to read the value as it is known that there is only one consumer. Of course, peeking from multiple threads is not supported.

The second or third could be reasonable to implement as part of crossbeam, but I don't feel the first is worth implementing as part of a crossbeam since it adds something completely new.
