### ISSUE TITLE
panic at sharded_lock.rs:290:15

### ISSUE THREAD

**Issue by JasonHonor** [crossbeam-rs/crossbeam#754]
Where a program run in mipsel device, a error was reported as follow:

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/.cargo/registry/src/mirrors-df7c3c540f42cdbd/crossbeam-utils-0.8.5/src/sync/sharded_lock.rs:290:15
stack backtrace:
   0: 0x55a0bce8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd0864d0e13de6d2a
   1: 0x55a3a8c4 - core::fmt::write::h98c2c5d65d5d5da0
   2: 0x55a07024 - <unknown>
   3: 0x55a0e7b8 - <unknown>
   4: 0x55a0e104 - <unknown>
   5: 0x55a0f250 - std::panicking::rust_panic_with_hook::h53331404aed95ef3
   6: 0x55a0ea80 - <unknown>
   7: 0x55a0c350 - <unknown>
   8: 0x55a0e9a4 - rust_begin_unwind
   9: 0x55643960 - core::panicking::panic_fmt::h99bb28c3ce6c75e3
  10: 0x5564391c - core::panicking::panic_bounds_check::hf955fe50c415b15d
  11: 0x5593d534 - <unknown>
  12: 0x5595f270 - <sled::lru::CacheAccessIter as core::iter::traits::iterator::Iterator>::next::he46cd5da9dd9be8f

**Comment by taiki-e** [comment]
Can you provide a repro?

> /home/.cargo/registry/src/mirrors-df7c3c540f42cdbd/crossbeam-utils-0.8.5/src/sync/sharded_lock.rs:290:15

Also, can you check if the same issue occurs if you use the official registry provided by crates.io instead of the mirror?

---

It seems panic is occurring here:

https://github.com/crossbeam-rs/crossbeam/blob/dba57a2c65e863209dac483c9fd9c86927a53b7e/crossbeam-utils/src/sync/sharded_lock.rs#L290

However, the number of shards is fixed at 8, and (IIUC) it will not be 0.

https://github.com/crossbeam-rs/crossbeam/blob/dba57a2c65e863209dac483c9fd9c86927a53b7e/crossbeam-utils/src/sync/sharded_lock.rs#L15-L16

https://github.com/crossbeam-rs/crossbeam/blob/dba57a2c65e863209dac483c9fd9c86927a53b7e/crossbeam-utils/src/sync/sharded_lock.rs#L102-L109

**Comment by JasonHonor** [comment]
I didn't switch to official repository, but I made a demo by the official example of sharded_lock.
It worked fine, might caused by sled, or other ?

**Comment by JasonHonor** [comment]
I see, it was caused by AtomicU64 on mips32 platform.
