### ISSUE TITLE
Testsuite fails when built without std feature.

### ISSUE THREAD

**Issue by plugwash** [crossbeam-rs/crossbeam#840]
Debian's CI runs tests with "--all-targets" and with various feature combinations. We found that crossbeam-epoch's testsuite fails when the "std" feature is not enabled.

https://ci.debian.net/data/autopkgtest/testing/amd64/r/rust-crossbeam-epoch/21986900/log.gz

I ground through the issues until I got the testsuite to pass, the patch can be found at

https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/crossbeam-epoch/debian/patches/fix-tests-no-default-features.patch

**Comment by taiki-e** [comment]
This is semi-intentional and is fine since we don't have mutually exclusive features. See https://github.com/rust-lang/futures-rs/pull/2216 for more. (Given how the cargo v1 resolver we use works, there isn't even a way to reliably test cases where specific (additive) features are disabled (dev or build dependencies may enable the features, and it will be shared with normal dependencies). Our `nightly` feature is not strictly additive, but our CI tests both cases where it is enabled and where it is not.)

If build errors of the test suite are a problem, I would accept PR to add `cfg(feature = "std")` to all tests at the module level.
