### ISSUE TITLE
'cargo check --all-targets --workspace' fails on stable

### ISSUE THREAD

**Issue by RalfJung** [crossbeam-rs/crossbeam#890]
Running `cargo check --all-targets --workspace` on stable fails with the following error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crossbeam-channel/benches/crossbeam.rs:1:12
  |
1 | #![feature(test)]
  |            ^^^^

    Checking crossbeam-queue v0.3.6 (/home/r/src/rust/lib-crates/crossbeam/crossbeam-queue)
For more information about this error, try `rustc --explain E0554`.
error: could not compile `crossbeam-channel` due to previous error
```
In particular this means opening crossbeam in vscode with rust-analyzer on a stable toolchain will show that error.

**Comment by taiki-e** [comment]
This is a common problem with all Rust crates running benchmarks using the built-in benchmark suite. A simple workaround is to use `--tests --examples` instead of `--all-targets` on stable.

I would accept a patch to use [criterion](https://github.com/bheisler/criterion.rs) in benchmarks, but there is no motivation on our part to address this since this situation is so common.

**Comment by RalfJung** [comment]
> A simple workaround is to use --tests --examples instead of --all-targets on stable.

That doesn't help for vscode showing errors each time I open crossbeam.

**Comment by RalfJung** [comment]
Ah, putting this into the settings helps:
```
    "rust-analyzer.checkOnSave.overrideCommand": [
        "cargo", "check", "--lib", "--bins", "--tests", "--examples", "--workspace", "--message-format=json"
    ],
```
I wonder if this should be the default for RA...

**Comment by RalfJung** [comment]
Sadly that work-around doesn't work, since it will break on packages that don't have a libs crate.

I don't think there *is* a way right now to configure RA globally that would just make this work. :/

**Comment by taiki-e** [comment]
`--tests` should implicitly enable `--lib` if exists because the library must be built to build the test (`--bins` as well).

So, I think "`--tests --examples` instead of `--all-targets`" mentioned in [the above comment](https://github.com/crossbeam-rs/crossbeam/issues/890#issuecomment-1193306865) should be enough.

**Comment by RalfJung** [comment]
The lib crate could have unit tests disabled though.

**Comment by taiki-e** [comment]
Unit tests don't seem disabled.

```console
$ cargo new --lib repro
$ cd repro
$ echo '#[test]
fn a() {
    let _; // failed to compile
}
' > src/tests.rs
$ echo '#[cfg(test)] mod tests;' > src/lib.rs
$ cargo check --tests            
    Checking repro v0.1.0 (/Users/taiki/projects/tmp/c/repro)
error[E0282]: type annotations needed
 --> src/tests.rs:3:9
  |
3 |     let _; // failed to compile
  |         ^
  |
help: consider giving this pattern a type
  |
3 |     let _: _; // failed to compile
  |          +++

For more information about this error, try `rustc --explain E0282`.
```

**Comment by RalfJung** [comment]
But you can disable them in `Cargo.toml`
```
[lib]
test = false
```

**Comment by RalfJung** [comment]
FWIW for now I have simply pinned my crossbeam folder to a nightly rustc to work around this. Crossbeam so far is the only crate I have encountered that is affected by this.
